### ISSUE TITLE
Use git tags in updates by default

### ISSUE THREAD

**Issue by Yajo** [pykong/copier#119]
One thing that floats around my mind is that the update system merged in #111 should use git tags instead of git commits.

Maybe we should implement this before #112.

This way, when running pre and post tasks, we could discriminate by version. We can leverage [one of these methods](https://stackoverflow.com/a/6972866/1468388) to provide template migration scripts:

```yaml
# copier.yml
_migrations:
  v1.0.2:
    pre:
      - git init
    post:
      - pre-commit install
```

When the template gets updated, it knows its old version and the new one. Using both, it can know which tasks to run.
