### ISSUE TITLE
Are values templated as well in copier.yml?

### ISSUE THREAD

**Issue by pawamoy** [pykong/copier#181]
Still coming from cookiecutter :sweat_smile: 

I was previously using templates values in my cookiecutter.json, something like:

```json
{
    "author_username": "Your username",
    "repository_namespace": "{{ cookiecutter.author_username }}"
}
```

Is this supported by copier?

```yaml
author_username:
  type: str
  help: Your username (e.g. on GitHub)

repository_namespace:
  type: str
  help: Your repository namespace
  default: "[[ author_username ]]"
```
