### ISSUE TITLE
Parameter help

### ISSUE THREAD

**Issue by Yajo** [pykong/copier#89]
We need to be able to go from

```yml
# copier.yml
smtp_mailname: example.com
```

To:

```yml
# copier.yml
smtp_mailname:
  help: The mailname is the hostname that your SMTP relay thinks it's using, and will appear in the logs
  default: example.com
  type: str
```

**Comment by Yajo** [comment]
Another option which could retain backwards compatibility (if that's necessary at all):

```yml
# copier.yml
_questions:
  - var: smtp_mailname
    help: The mailname is the hostname that your SMTP relay thinks it's using, and will appear in the logs
    default: example.com
```

The advantage of using a list is that those are sequential, so it would make easier to implement #90.
