### ISSUE TITLE
Ability to use source template path in tasks section

### ISSUE THREAD

**Issue by Yajo** [pykong/copier#95]
Sorry for opening so many feature requests, but it's so you have them on your radar. :sweat_smile: 

The tasks section allows you to write scripts in a YAML file. That can be useful for short scripts, but if you need something serious, it becomes uncomfortable.

If there were some var such as `[[ source_dir ]]` then I could use tasks such as:

```yaml
# copier.yml
_exclude:
  - post-clone*
_tasks:
  - pip install "[[ source_dir ]]/post-clone-dependencies.txt"
  - "[[ source_dir ]]/post-clone.py"
```
